# Controller configuration parameters
  /car_kin_PI/run_period: 0.01          # Node execution period

# Controller parameters
  /car_kin_PI/P_dist: 0.05              # Distance of point P from odometric center
  /car_kin_PI/l: 0.26                   # Car length
  /car_kin_PI/Kpx: 3 #2                 # Proportional weight on x direction
  /car_kin_PI/Tix: 5                    # Integral weight on x direction
  /car_kin_PI/Kpy: 4                    # Proportional weight on y direction
  /car_kin_PI/Tiy: 2.5                  # Integral weight on y direction

  /car_kin_PI/Ts:  0.001                # Sampling Time

  /car_kin_PI/V_sat:  6                 # Forward velocity command saturation
  /car_kin_PI/Phi_sat:  2               # Steering command saturation

# 8-shape trajectory parameters
  /car_kin_PI/a: 2                      
  /car_kin_PI/T: 3.8